[package]
name = "nano-fonts"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde.workspace = true
reqwest = { workspace = true, features = ["json"] }
woff2.workspace = true
base64.workspace = true
tokio = { workspace = true, features = ["rt", "rt-multi-thread", "macros"] }
serde_json.workspace = true
