[package]
name = "worker-build"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.80"
dirs-next = "2.0.0"
flate2 = "1.0.28"
tar = "0.4.40"
ureq = { version = "2.9.6", features = ["tls", "gzip"] }
